"""Renderers for the deviation record: terminal summary and Markdown audit doc."""

from __future__ import annotations

from pathlib import Path

from rich.console import Console
from rich.markup import escape

from .deviations import Deviation, DeviationRecord


def _loc(d: Deviation) -> str:
    if not d.file:
        return "(global)"
    return f"{d.file}:{d.line}" if d.line else d.file


def render_terminal(record: DeviationRecord) -> None:
    console = Console(stderr=False, emoji=False, highlight=False)
    console.rule("[bold]MISRA deviation record")
    total = len(record.deviations)
    inline = sum(1 for d in record.deviations if d.origin == "inline")
    console.print(
        f"{total} deviation(s): [cyan]{inline} inline[/], "
        f"{total - inline} project-level"
    )

    for d in sorted(record.deviations, key=lambda x: (x.origin, x.file, x.line or 0)):
        tag = "[green]✓[/]" if d.valid else "[red]✗[/]"
        ids = escape(", ".join(d.rule_ids))
        console.print(
            f"  {tag} [cyan]{ids}[/]  [dim]{escape(_loc(d))}[/]  "
            f"{escape(d.justification)}"
        )

    if record.unjustified:
        console.print(
            f"\n[red]{len(record.unjustified)} deviation(s) lack a justification[/] "
            "(add `; @deviation <reason>`):"
        )
        for d in record.unjustified:
            console.print(
                f"  [red]✗[/] {escape(', '.join(d.rule_ids))}  {escape(_loc(d))}"
            )
    if record.unknown:
        console.print("\n[red]Unknown rule id(s) (typo? not in headlines):[/]")
        for d in record.unknown:
            console.print(
                f"  [red]?[/] {escape(', '.join(d.unknown_ids))}  {escape(_loc(d))}"
            )
    if record.stale:
        console.print(
            f"\n[yellow]{len(record.stale)} stale suppression(s)[/] "
            "(no longer match a finding, remove them):"
        )
        for s in record.stale:
            console.print(f"  [yellow]~[/] {escape(s)}")

    if record.ok() and not record.stale:
        console.print("\n[green]All deviations justified and valid.[/]")


def _status(d: Deviation) -> str:
    if d.valid:
        return "ok"
    return "**unjustified**" if not d.justified else "**unknown id**"


def render_markdown(record: DeviationRecord, path: Path) -> None:
    lines: list[str] = []
    add = lines.append
    add("# MISRA C:2023 deviation record")
    add("")
    add(
        "Generated by `misch deviations`. Each entry is a suppressed "
        "guideline that must carry a documented rationale."
    )
    add("")

    sections = (
        ("inline", "Inline deviations"),
        ("project", "Project-level deviations"),
    )
    for origin, title in sections:
        group = [d for d in record.deviations if d.origin == origin]
        if not group:
            continue
        add(f"## {title}")
        add("")
        add("| Rule(s) | Location | Justification | Status |")
        add("| --- | --- | --- | --- |")
        for d in sorted(group, key=lambda x: (x.file, x.line or 0)):
            just = d.justification.replace("|", "\\|") or "n/a"
            add(f"| {', '.join(d.rule_ids)} | `{_loc(d)}` | {just} | {_status(d)} |")
        add("")

    if record.stale:
        add("## Stale suppressions")
        add("")
        add("These no longer match any finding and should be removed:")
        add("")
        for s in record.stale:
            add(f"- `{s}`")
        add("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
